language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - python3 -m unittest
  - coverage run -m unittest

after_success:
  - coveralls
  - codecov --token=CODECOV_TOKEN
