language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - python3 -m unittest
  - nosetests --with-coverage --cover-package=app test

after_success:
  - coveralls
  #- codecov --token=bahaslas
